export const DAY_NIGHT_TEXT = {
  0: ['Sunny', 'Clear'],
  1: ['Mainly Sunny', 'Mainly Clear'],
  2: ['Partly Cloudy', 'Partly Cloudy'],
  3: ['Cloudy', 'Cloudy'],
  45: ['Foggy', 'Foggy'],
  48: ['Rime Fog', 'Rime Fog'],
  51: ['Light Drizzle', 'Light Drizzle'],
  53: ['Drizzle', 'Drizzle'],
  55: ['Heavy Drizzle', 'Heavy Drizzle'],
  56: ['Light Freezing Drizzle', 'Light Freezing Drizzle'],
  57: ['Freezing Drizzle', 'Freezing Drizzle'],
  61: ['Light Rain', 'Light Rain'],
  63: ['Rain', 'Rain'],
  65: ['Heavy Rain', 'Heavy Rain'],
  66: ['Light Freezing Rain', 'Light Freezing Rain'],
  67: ['Freezing Rain', 'Freezing Rain'],
  71: ['Light Snow', 'Light Snow'],
  73: ['Snow', 'Snow'],
  75: ['Heavy Snow', 'Heavy Snow'],
  77: ['Snow Grains', 'Snow Grains'],
  80: ['Light Showers', 'Light Showers'],
  81: ['Showers', 'Showers'],
  82: ['Heavy Showers', 'Heavy Showers'],
  85: ['Light Snow Showers', 'Light Snow Showers'],
  86: ['Snow Showers', 'Snow Showers'],
  95: ['Thunderstorm', 'Thunderstorm'],
  96: ['Light Thunderstorms With Hail', 'Light Thunderstorms With Hail'],
  99: ['Thunderstorm With Hail', 'Thunderstorm With Hail'],
};

export const BUCKET_RANGES = [
  { codes: [0, 1], bucket: 'Clear' },
  { codes: [2, 3], bucket: 'Cloudy' },
  { codes: [45, 48], bucket: 'Foggy' },
  { codes: [51, 53, 55, 56, 57], bucket: 'Drizzle' },
  { codes: [61, 63, 65, 66, 67, 80, 81, 82], bucket: 'Rainy' },
  { codes: [71, 73, 75, 77, 85, 86], bucket: 'Snowy' },
  { codes: [95, 96, 99], bucket: 'Thunderstorm' },
];
